### PR TITLE
[#108]: Bump up github to 0.23

### PR DESCRIPTION
**Pull request by bangn**
Looks like bump up github to 0.23 fix problem I have in #118 as well

### CODE REVIEW

**Comment by chshersh** [comment]
@bangn Thanks for the update! However, this PR should be verified carefully. Last time we've upgraded to `github-0.21`, it didn't work because it has a bug. Upgrade to `github-0.22` broke the UI of `hit-on`. I believe that `github-0.23` still has this problem, as described in #108. So this PR can be merged after fixing this known problem and after @vrom911 and I carefully verify that everything works as expected.

**Comment by bangn** [comment]
@chshersh thank you for your information. The bug described in #108 has been fixed by https://github.com/kowainik/hit-on/pull/119/commits/ad47eb721ea49dcd6a434b8cc8a36c37426343e0. However, Im not so sure if it will break anything.

Is there anyway we can automate the test process?

**Comment by chshersh** [comment]
@bangn There's in an issue on how to test `hit-on` automatically, you can share your thoughts there:

* https://github.com/kowainik/hit-on/issues/62

Regarding this PR: I checked it locally on different commands, it seems to work and nothing breaks so far. So I would say I approve but I won't do it via GitHub UI yet to not merge it accidentally. We need some more time to check everything carefully :slightly_smiling_face:

**Comment by vrom911** [comment]
Sorry for the delay in the review. Give me some more time to test it locally as well...
Thanks for your work, @bangn ! Really appreciate that :clap:

**Pull request merged**
